### ISSUE TITLE
what is the formula of forward?

### ISSUE THREAD

**Issue by juntang-zhuang** [Laborieux-Axel/Equilibrium-Propagation#1]
Hi, I took a quick look at the paper and code, and I was confused by the forward for the first phase.
If I understand it correctly, the continuous forward is   ds/dt = - \frac{\partial \Phi}{\partial s}
relaxing it to a discrete approximation, it should be     s_{t+1} = s_t - \delta \times \frac{\partial \Phi}{\partial s}
Yet in your paper, the update is      s_{t+1} =  \frac{\partial \Phi}{\partial s}
Did I missunderstood your paper?

**Comment by Laborieux-Axel** [comment]
Hello! Thanks for the message.
The update we apply is s_{t+1} = \frac{\partial \Phi}{\partial s}  because \Phi is not the energy function. 
If we write E the energy function, the Phi we use is defined as: 
Phi(s_t) = 0.5 \times s_t^2 - \delta \times E(s_t) 
so that s_{t+1} = \frac{\partial \Phi}{\partial s} = s_t - \delta \times \frac{\partial E}{\partial s}

In our case we use the discrete setting where \delta = 1 and E(s_t) = 0.5 (s_t)^2 - \sum {s_post W s_pre} so that the term in s_t^2 cancels out.
You can have a look at this paper https://arxiv.org/pdf/1905.13633.pdf which defines EP with Phi, and in particular the appendix B.2 which explains the difference between E and Phi.

**Comment by juntang-zhuang** [comment]
thanks for the clarification.
